apiVersion: v1
kind: Namespace
metadata:
  name: cosmic-explorer
  labels:
    name: cosmic-explorer
    app: cosmic-explorer
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
