apiVersion: v1
kind: Service
metadata:
  name: cosmic-explorer
  namespace: cosmic-explorer
  labels:
    app: cosmic-explorer
spec:
  type: ClusterIP
  selector:
    app: cosmic-explorer
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
